name: Building, Testing and Singularity

on: [push, pull_request] # pull_request really necessary?

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # doc: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install MPICH
        run: sudo apt install mpich
      
      # doc: https://google.github.io/googletest/quickstart-cmake.html#create-and-run-a-binary
      - name: Build and run the tests
        run: |
          cmake -S . -B build
          cmake --build build
          cd build 
          ctest --rerun-failed --output-on-failure
  
  singularity:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go 1.21.10
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.21.10'
        id: go
      
      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#install-dependencies
      - name: Install Dependencies 
        run: |
          cd
          sudo apt-get update
          sudo apt-get install -y autoconf automake cryptsetup fuse fuse2fs git libfuse-dev libglib2.0-dev libseccomp-dev libtool pkg-config runc squashfs-tools squashfs-tools-ng uidmap wget zlib1g-dev

      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#download-singularityce-from-a-release
      - name: Download and Compile Singularity (4.1.3)
        env:
          SINGULARITY_VERSION: 4.1.3
          GOPATH: /tmp/go
      
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install

      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#compile-singularity
      #- name: Compile Singularity
        #run: |
          #./mconfig && \
            #make -C ./builddir && \
            #sudo make -C ./builddir install

      - name: Create the container
        run: sudo singularity build test-matrix-multiplication.sif singularity.def

      - name: Performs tests on the container
        run: ./test-matrix-multiplication.sif