name: Building, Testing and Containerizing the application

on: [push, pull_request] # pull_request really necessary?

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # doc: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install MPICH
        run: sudo apt install mpich
      
      # doc: https://google.github.io/googletest/quickstart-cmake.html#create-and-run-a-binary
      - name: Build and run the tests
        run: |
          cmake -S . -B build
          cmake --build build
          cd build 
          ctest --rerun-failed --output-on-failure
  
  singularity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#install-dependencies
      - name: Install Dependencies 
        run: |
          cd
          sudo apt-get update
          sudo apt-get install -y autoconf automake cryptsetup fuse fuse2fs git libfuse-dev libglib2.0-dev libseccomp-dev libtool pkg-config runc squashfs-tools squashfs-tools-ng uidmap wget zlib1g-dev
      
      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#install-go
      - name: Download Go
        run: |
          export VERSION=1.21.10 OS=linux ARCH=amd64
          wget -q https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz

      - name: Extract Go
        run: |
          sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz
          rm go$VERSION.$OS-$ARCH.tar.gz

      - name: Set up environment for Go
        run: |
          echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
          echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
          source ~/.bashrc

      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#download-singularityce-from-a-release
      - name: Download SingularityCE from the release 4.1.3
        run: |
          export VERSION=4.1.3
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz
          tar -xzf singularity-ce-${VERSION}.tar.gz
          cd singularity-ce-${VERSION}

      # https://docs.sylabs.io/guides/4.1/admin-guide/installation.html#compile-singularity
      - name: Compile Singularity
        run: |
          ./mconfig
          make -C ./builddir
          sudo make -C ./builddir install

      - name: Create the container
        run: sudo singularity build test-matrix-multiplication.sif singularity.def

      - name: Performs tests on the container
        run: ./test-matrix-multiplication.sif