name: Automating the test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: try
        run: |
          sudo apt install mpich
          cmake -S . -B build
          cmake --build build
          cd build && ctest

