name: Automating the test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: try
        run: |
          sudo apt install build-essential cmake
          cmake -S .. -B build
          cmake --build build
          cd build && ctest

