name: Automating the test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: |
          cmake .
      - name: second
        run: |
          cmake --build build
      - name: third
        run: |
          cd build && ctest
